package org.greenlist.entityé;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="projet3"
)
public class Message  implements java.io.Serializable {


     private int id;
     private Echange echange;
     private Ticket ticket;
     private Utilisateur utilisateur;
     private Date dateEnvoi;
     private String corps;
     private boolean islu;
     private Set tickets = new HashSet(0);

    public Message() {
    }

	
    public Message(int id, Echange echange, Ticket ticket, Utilisateur utilisateur, Date dateEnvoi, String corps, boolean islu) {
        this.id = id;
        this.echange = echange;
        this.ticket = ticket;
        this.utilisateur = utilisateur;
        this.dateEnvoi = dateEnvoi;
        this.corps = corps;
        this.islu = islu;
    }
    public Message(int id, Echange echange, Ticket ticket, Utilisateur utilisateur, Date dateEnvoi, String corps, boolean islu, Set tickets) {
       this.id = id;
       this.echange = echange;
       this.ticket = ticket;
       this.utilisateur = utilisateur;
       this.dateEnvoi = dateEnvoi;
       this.corps = corps;
       this.islu = islu;
       this.tickets = tickets;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDECHANGE", nullable=false)
    public Echange getEchange() {
        return this.echange;
    }
    
    public void setEchange(Echange echange) {
        this.echange = echange;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTICKET", nullable=false)
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUTILISATEUR", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_ENVOI", nullable=false, length=19)
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    
    @Column(name="CORPS", nullable=false, length=65535)
    public String getCorps() {
        return this.corps;
    }
    
    public void setCorps(String corps) {
        this.corps = corps;
    }

    
    @Column(name="ISLU", nullable=false)
    public boolean isIslu() {
        return this.islu;
    }
    
    public void setIslu(boolean islu) {
        this.islu = islu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="message")
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


