package org.greenlist.entityé;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotifRadiation generated by hbm2java
 */
@Entity
@Table(name="motif_radiation"
    ,catalog="projet3"
)
public class MotifRadiation  implements java.io.Serializable {


     private int id;
     private String libelle;
     private Set utilisateurs = new HashSet(0);

    public MotifRadiation() {
    }

	
    public MotifRadiation(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public MotifRadiation(int id, String libelle, Set utilisateurs) {
       this.id = id;
       this.libelle = libelle;
       this.utilisateurs = utilisateurs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LIBELLE", nullable=false, length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motifRadiation")
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


