package org.greenlist.entityé;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name="theme"
    ,catalog="projet3"
)
public class Theme  implements java.io.Serializable {


     private int id;
     private String libelle;
     private Set itemFaqs = new HashSet(0);

    public Theme() {
    }

	
    public Theme(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public Theme(int id, String libelle, Set itemFaqs) {
       this.id = id;
       this.libelle = libelle;
       this.itemFaqs = itemFaqs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LIBELLE", nullable=false, length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="theme")
    public Set getItemFaqs() {
        return this.itemFaqs;
    }
    
    public void setItemFaqs(Set itemFaqs) {
        this.itemFaqs = itemFaqs;
    }




}


