package org.greenlist.entityé;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrancheAge generated by hbm2java
 */
@Entity
@Table(name="tranche_age"
    ,catalog="projet3"
)
public class TrancheAge  implements java.io.Serializable {


     private int id;
     private String libelle;
     private Set objets = new HashSet(0);
     private Set souhaits = new HashSet(0);

    public TrancheAge() {
    }

	
    public TrancheAge(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public TrancheAge(int id, String libelle, Set objets, Set souhaits) {
       this.id = id;
       this.libelle = libelle;
       this.objets = objets;
       this.souhaits = souhaits;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LIBELLE", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trancheAge")
    public Set getObjets() {
        return this.objets;
    }
    
    public void setObjets(Set objets) {
        this.objets = objets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trancheAge")
    public Set getSouhaits() {
        return this.souhaits;
    }
    
    public void setSouhaits(Set souhaits) {
        this.souhaits = souhaits;
    }




}


