package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresse generated by hbm2java
 */
@Entity
@Table(name="adresse"
    ,catalog="projet3"
)
public class Adresse  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private String numeroVoie;
     private String rue;
     private String codePostal;
     private String ville;
     private double longitude;
     private double latittude;
     private List<Rdv> rdvs = new ArrayList<>();

    public Adresse() {
    }

	
    public Adresse(int id, String rue, String codePostal, String ville, double longitude, double latittude) {
        this.id = id;
        this.rue = rue;
        this.codePostal = codePostal;
        this.ville = ville;
        this.longitude = longitude;
        this.latittude = latittude;
    }
    public Adresse(int id, Utilisateur utilisateur, String numeroVoie, String rue, String codePostal, String ville, double longitude, double latittude, List<Rdv> rdvs) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.numeroVoie = numeroVoie;
       this.rue = rue;
       this.codePostal = codePostal;
       this.ville = ville;
       this.longitude = longitude;
       this.latittude = latittude;
       this.rdvs = rdvs;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUTILISATEUR")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="NUMERO_VOIE", length=15)
    public String getNumeroVoie() {
        return this.numeroVoie;
    }
    
    public void setNumeroVoie(String numeroVoie) {
        this.numeroVoie = numeroVoie;
    }

    
    @Column(name="RUE", nullable=false, length=100)
    public String getRue() {
        return this.rue;
    }
    
    public void setRue(String rue) {
        this.rue = rue;
    }

    
    @Column(name="CODE_POSTAL", nullable=false, length=10)
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }

    
    @Column(name="VILLE", nullable=false, length=100)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="LONGITUDE", nullable=false, precision=22, scale=0)
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="LATITTUDE", nullable=false, precision=22, scale=0)
    public double getLatittude() {
        return this.latittude;
    }
    
    public void setLatittude(double latittude) {
        this.latittude = latittude;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adresse")
    public List<Rdv> getRdvs() {
        return this.rdvs;
    }
    
    public void setRdvs(List<Rdv> rdvs) {
        this.rdvs = rdvs;
    }




}


