package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conclusionechange generated by hbm2java
 */
@Entity
@Table(name="conclusionechange"
    ,catalog="projet3"
)
public class Conclusionechange  implements java.io.Serializable {


     private int id;
     private String libelle;
     private List<Echange> echanges = new ArrayList<>();

    public Conclusionechange() {
    }

	
    public Conclusionechange(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public Conclusionechange(int id, String libelle, List<Echange> echanges) {
       this.id = id;
       this.libelle = libelle;
       this.echanges = echanges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LIBELLE", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conclusionechange")
    public List<Echange> getEchanges() {
        return this.echanges;
    }
    
    public void setEchanges(List<Echange> echanges) {
        this.echanges = echanges;
    }




}


