package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domaine generated by hbm2java
 */
@Entity
@Table(name = "domaine", catalog = "projet3")
public class Domaine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String libelle;
	private List<Groupe> groupes = new ArrayList<>();
	private List<Souhait> souhaits = new ArrayList<>();

	public Domaine() {
	}

	public Domaine(int id, String libelle) {
		this.id = id;
		this.libelle = libelle;
	}

	public Domaine(int id, String libelle, List<Groupe> groupes, List<Souhait> souhaits) {
		this.id = id;
		this.libelle = libelle;
		this.groupes = groupes;
		this.souhaits = souhaits;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LIBELLE", nullable = false, length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domaine")
	public List<Groupe> getGroupes() {
		return this.groupes;
	}

	public void setGroupes(List<Groupe> groupes) {
		this.groupes = groupes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domaine")
	public List<Souhait> getSouhaits() {
		return this.souhaits;
	}

	public void setSouhaits(List<Souhait> souhaits) {
		this.souhaits = souhaits;
	}

}
