package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="groupe"
    ,catalog="projet3"
)
public class Groupe  implements java.io.Serializable {


     private int id;
     private Domaine domaine;
     private String libelle;
     private List<Produit> produits = new ArrayList<>();
     private List<Souhait> souhaits = new ArrayList<>();

    public Groupe() {
    }

	
    public Groupe(int id, Domaine domaine, String libelle) {
        this.id = id;
        this.domaine = domaine;
        this.libelle = libelle;
    }
    public Groupe(int id, Domaine domaine, String libelle, List<Produit> produits, List<Souhait> souhaits) {
       this.id = id;
       this.domaine = domaine;
       this.libelle = libelle;
       this.produits = produits;
       this.souhaits = souhaits;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDOMAINE", nullable=false)
    public Domaine getDomaine() {
        return this.domaine;
    }
    
    public void setDomaine(Domaine domaine) {
        this.domaine = domaine;
    }

    
    @Column(name="LIBELLE", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public List<Produit> getProduits() {
        return this.produits;
    }
    
    public void setProduits(List<Produit> produits) {
        this.produits = produits;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public List<Souhait> getSouhaits() {
        return this.souhaits;
    }
    
    public void setSouhaits(List<Souhait> souhaits) {
        this.souhaits = souhaits;
    }




}


