package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panier generated by hbm2java
 */
@Entity
@Table(name="panier"
    ,catalog="projet3"
)
public class Panier  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateur;
     private Set utilisateurs = new HashSet(0);
     private Set objets = new HashSet(0);

    public Panier() {
    }

	
    public Panier(int id) {
        this.id = id;
    }
    public Panier(int id, Utilisateur utilisateur, Set utilisateurs, Set objets) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.utilisateurs = utilisateurs;
       this.objets = objets;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUTILISATEUR")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="panier")
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="echanges")
    public Set getObjets() {
        return this.objets;
    }
    
    public void setObjets(Set objets) {
        this.objets = objets;
    }




}


