package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typenotification generated by hbm2java
 */
@Entity
@Table(name="typenotification"
    ,catalog="projet3"
)
public class Typenotification  implements java.io.Serializable {


     private int id;
     private String libelle;
     private List<Preference> preferences = new ArrayList<>();
     private List<Notification> notifications = new ArrayList<>();

    public Typenotification() {
    }

	
    public Typenotification(int id, String libelle) {
        this.id = id;
        this.libelle = libelle;
    }
    public Typenotification(int id, String libelle, List<Preference> preferences, List<Notification> notifications) {
       this.id = id;
       this.libelle = libelle;
       this.preferences = preferences;
       this.notifications = notifications;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LIBELLE", nullable=false, length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="typenotifications")
    public List<Preference> getPreferences() {
        return this.preferences;
    }
    
    public void setPreferences(List<Preference> preferences) {
        this.preferences = preferences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typenotification")
    public List<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(List<Notification> notifications) {
        this.notifications = notifications;
    }




}


